<?php

namespace AppBundle\Repository;

/**
 * MainAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
